id: A40F05C71
base_file: f3056.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:28:02.217950
  last_modified_at: 2022-06-11 13:28:02.217961
