id: A40F05C71
base_file: f47B8.txt
type: translation
source_metadata:
  languages:
  - en
  - bo
  datatype: PlainText
  created_at: 2022-06-11 13:28:02.220988
  last_modified_at: 2022-06-11 13:28:02.220996
